### PR TITLE
Fixed : "After it will be released by setting the 01-71tag, to remove the root_VS2010 in the develop branch. enhancement." #23

### LINKED ISSUE #23: After it will be released by setting the 01-71tag, to remove the root_VS2010 in the develop branch.
# Requirement
We will stop the root_VS2010(.NET4.0) 's update.
But, We were required to support continuation of the .NET3.5 (SP1).
Because some of .NET Framework will be no longer supported at January 12, 2016.
http://blogs.msdn.com/b/dotnet/archive/2014/08/07/moving-to-the-net-framework-4-5-2.aspx

Therefor, after it was released by be set 01-71tag,
- Delete root_VS2010(.NET4.0) dir contents, and commit.
- Move root_easysetup(.NET3.5) dir contents to root_VS2010(.NET3.5) dir, and commit.

Update of root_VS2010(.NET3.5) will be expected to stop after setting the next tag (01-72 or more).

### PR DESCRIPTION
**Pull request by daisukenishino**
fixed #23

### CODE REVIEW

File: root_VS2010/files/resource/Sql/sqlserver/Workflow/SQL/Table/M_User_Insert(sample).sql [hunk 1]
```diff
@@ -1,24 +1,24 @@
-﻿USE [Workflow]
+USE [Workflow]
 GO
 
 INSERT INTO [dbo].[M_User]([Id], [Section], [Name], [PositionTitlesId])
     VALUES
-	(1   , 'AAAA' , 'A御中'   , 1 ),
+	(1   , 'AAAA' , 'A�䒆'   , 1 ),
```
Comment (yusukemaegawa) [inline root_VS2010/files/resource/Sql/sqlserver/Workflow/SQL/Table/M_User_Insert(sample).sql]: @daisukenishino 

The text is garbled.
Maybe the encoding of this file is Shift-JIS.

File: root_VS2010/programs/C#/Frameworks/Infrastructure/ServiceInterface/ASPNETWebService/web.Config [hunk 2]
```diff
@@ -10,6 +10,19 @@
 <configuration>
   <!-- ajaxの設定（バージョンなどに注意する。） -->
   <!-- appSettingsの設定 -->
+  <configSections>
```
Comment (yusukemaegawa) [inline root_VS2010/programs/C#/Frameworks/Infrastructure/ServiceInterface/ASPNETWebService/web.Config]: @daisukenishino 

There were not these settings until now.
Because TargetFrameworkVersion becomes "3.5", are these settings necessary?

Comment (yusukemaegawa) [inline root_VS2010/programs/C#/Frameworks/Infrastructure/ServiceInterface/ASPNETWebService/web.Config]: @daisukenishino 

Please review the position of these settings.
Currently, you describes these settings immediately after "appSettingsの設定" comment.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

I think the mismatch between the programs in root_VS2010 and others (e.g. root_VS2012) occurs due to this pull request.

- The modules which disappear from root_VS2010
    - JQGrid sample. (In ASP.NET sample.)
    - Content, Scripts, WebService folders. (In ASP.NET sample.)

There are the above modules in root_VS2012, root_VS2013, root_VS2015.

- The modules which are added in root_VS2010
    - Test projects. (Public.Test, BDLayer.Test, and so on.)

There are not the above modules in root_VS2012, root_VS2013, root_VS2015.

File: root_VS2010/programs/C#/Frameworks/Infrastructure/ServiceInterface/ASPNETWebService/web.Config (hunk 2 above)
Comment (daisukenishino) [inline root_VS2010/programs/C#/Frameworks/Infrastructure/ServiceInterface/ASPNETWebService/web.Config]: @yusukemaegawa 

I planed to change the position of the comment.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

- The following are deleted because can not be supported by the .NET3.5.
  - JQGrid sample. (In ASP.NET sample.)
    -  Content, Scripts, WebService folders.  
These are the module that have been added in support of JQGrid.
- The following must be removed because it does not transplant to the template.
  - Test projects. (Public.Test, BDLayer.Test, and so on.)

File: root_VS2010/files/resource/Sql/sqlserver/Workflow/SQL/Table/M_User_Insert(sample).sql (hunk 1 above)
Comment (daisukenishino) [inline root_VS2010/files/resource/Sql/sqlserver/Workflow/SQL/Table/M_User_Insert(sample).sql]: @yusukemaegawa 

I will correct all of degraded related to the character code.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

This was corrected as follows.
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/91
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/92

Maybe, there is a time lag, but will be also reflected in the "Files changed" of this pull request.
Please check and merge.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

This was corrected as follows.
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/91
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/92
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/94
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/95
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/96

Maybe, there is a time lag, but will be also reflected in the "[Files changed](https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/34/files)" of this pull request.
Please check and merge.

**Comment by daisukenishino** [comment]
@yusukemaegawa

Changes have been reflected in the "[Files changed](https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/34/files)".
Please merge after checking this operation.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/34#issuecomment-184964178

>- The following are deleted because can not be supported by the .NET3.5.
>  - JQGrid sample. (In ASP.NET sample.)
>    -  Content, Scripts, WebService folders.  
>These are the module that have been added in support of JQGrid.

Please let me confirm.
Do you say that the following program can not be supported by the .NET 3.5?

[JSONService.svc.cs](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2012/programs/C%23/Samples/WebApp_sample/ProjectX_sample/App_Code/JSONService.svc.cs#L75)
```c#
// returns JSON string in Message format
return WebOperationContext.Current.CreateTextResponse(jsonData, "application/json; charset=utf-8", Encoding.UTF8);
```

Certainly, "CreateTextResponse" method does not exist in .NET 3.5.
But, are there the other approaches that can be used in .NET 3.5?

**Comment by daisukenishino** [comment]
@yusukemaegawa 

> https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/34#issuecomment-185492852

Because prototype created in the biginninng contains "CreateTextResponse" method, As a result, rather than "root (.NET3.5)", "root_VS2010 (.NET4.0)" became target.

 I think .NET 3.5 is left only short time of End of Support, and there isn't many cases to adopt new architecture by using old IDE project. Therefor, I will not add the JQGrid sample, because I considering cost-effectiveness.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

The TargetFrameworkVersion of the projects in root_VS2010 has changed to 3.5.

So, should developers use MSBuild 3.5?
Are there problems that developers use MSBuild 4.0 to build .NET 3.5 projects?
(Currently, the default version of MSBuild is 4.0.)

**Comment by daisukenishino** [comment]
@yusukemaegawa 

>https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/34#issuecomment-185554160

I think that this status quo doesn't have any problems.

Because the environment of Visual Studio 2010 will install .NET 4.0, thererfor, I think there is no problem about this templete's use because MSBuild 4.0 is also installed there. In addition, I do not have information about the compatibility between .NET 3.5 and MSBuild 3.5, 4.0.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

I almost understood.
But, the following warning showed during build DPQuery_Tool.sln.
Please confirm.

>Form1.cs(655,37): warning CS0436: '...\root_VS2010\programs\C#\Frameworks\Tools\DPQuery_Tool\DummyDaps.cs' の型 'Touryo.Infrastructure.Public.Db.DamOraClient' は、'...\root_VS2010\programs\C#\Frameworks\Infrastructure\Build\Public.dll' のインポートされた型 'Touryo.Infrastructure.Public.Db.DamOraClient' と競合しています。'...\root_VS2010\programs\C#\Frameworks\Tools\DPQuery_Tool\DummyDaps.cs' で定義された型を使用しています。 [...\root_VS2010\programs\C#\Frameworks\Tools\DPQuery_Tool\DPQuery_Tool.csproj]
>Form1.cs(1399,76): warning CS0436: '...\root_VS2010\programs\C#\Frameworks\Tools\DPQuery_Tool\DummyDaps.cs' の型 'Touryo.Infrastructure.Public.Db.DamOraClient' は、'...\root_VS2010\programs\C#\Frameworks\Infrastructure\Build\Public.dll' のインポートされた型 'Touryo.Infrastructure.Public.Db.DamOraClient' と競合しています。'...\root_VS2010\programs\C#\Frameworks\Tools\DPQuery_Tool\DummyDaps.cs' で定義された型を使用しています。 [...\root_VS2010\programs\C#\Frameworks\Tools\DPQuery_Tool\DPQuery_Tool.csproj]

**Comment by daisukenishino** [comment]
@yusukemaegawa 

> https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/34#issuecomment-185579361

The "system.data.oracleclient" is available in .NET 3.5. But, Deprecated in .NET 4.0 or more.
root_VS2010 (.NET 3.5) include DamOraClient class that is wrapper class of the "system.data.oracleclient".

Therefor, I have commented out dummy type of the DamOraClient.
https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/34/files#diff-71f35917d802fb7789f0f8809b29ade9R42
With this modification, the warning was no longer displayed.

Please confirm.
